"""Database models for the Human-in-the-Loop research platform.

The task lifecycle is the heart of this app:

    queued -> planning -> awaiting_approval -> researching -> complete
                                |                   |
                                +--> cancelled <----+
                                        failed

`awaiting_approval` is the human-in-the-loop gate: the agent has drafted a plan
and (optionally) asked clarifying questions, and it will not spend another token
until a person edits/approves it.

Entity Relationships:
  - `User`: Root account table owning research tasks.
  - `ResearchTask`: Central entity carrying query, human edits, final report, cost accounting, and state.
  - `TaskEvent`: Append-only event log used by frontend to render real-time execution timelines.
  - `Source`: Web pages retrieved by the agent with flags for human exclusion/veto.
  - `LLMTurn`: Granular telemetry per model invocation (tokens, latency, cost, attempts).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


def _uuid() -> str:
    """Generate a random 32-character hexadecimal UUID string."""
    return uuid.uuid4().hex


def utcnow() -> datetime:
    """Timezone-aware now(). Naive datetimes compare wrongly across DST and drivers."""
    return datetime.now(timezone.utc)


class TaskStatus(str):
    """The task state machine, as string constants.

    Deliberately not an Enum: these values are written to a plain string column
    and compared in SQL, and a bare str keeps queries and JSON payloads simple.
    """
    QUEUED = "queued"                  # Task created, waiting for planner job
    PLANNING = "planning"              # LLM currently drafting research plan
    AWAITING_APPROVAL = "awaiting_approval"  # Human gate: plan ready for user review/edit
    RESEARCHING = "researching"        # Plan approved; agent executing tool loop
    COMPLETE = "complete"              # Final markdown report synthesized & audited
    FAILED = "failed"                  # Unrecoverable error encountered or orphaned
    CANCELLED = "cancelled"            # User aborted task before completion

    # Terminal states where execution has concluded and polling stops
    TERMINAL = {"complete", "failed", "cancelled"}


class User(Base):
    """An account. Everything a person creates hangs off this row."""
    __tablename__ = "users"

    # Unique 32-character user identifier
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    # User email address (unique index, normalized to lowercase)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    # Stored password hash (bcrypt-sha256 format)
    hashed_password: Mapped[str] = mapped_column(String(255))
    # Account registration timestamp (UTC)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # Cascading relationship to all research tasks owned by this user
    tasks: Mapped[list["ResearchTask"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class ResearchTask(Base):
    """One research request and everything known about it.

    Carries the plan awaiting approval, the finished report, the citation audit,
    and the running cost - so a single row answers 'what happened, and what did
    it cost'.
    """
    __tablename__ = "research_tasks"

    # Unique 32-character task identifier
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    # Foreign key referencing the owning user account
    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    # The original research inquiry or topic prompt
    query: Mapped[str] = mapped_column(Text)
    # Current lifecycle state (TaskStatus constant)
    status: Mapped[str] = mapped_column(String(32), default=TaskStatus.QUEUED, index=True)

    # --- the human-in-the-loop payload ------------------------------------
    # Optional list of clarifying questions generated by the planner
    clarifying_questions: Mapped[list | None] = mapped_column(JSON, default=None)
    # User-provided answers to clarifying questions
    clarification_answers: Mapped[dict | None] = mapped_column(JSON, default=None)
    # List of research plan steps (list[str]) drafted by model or edited by user
    plan: Mapped[list | None] = mapped_column(JSON, default=None)  # list[str] of steps
    # True if the user modified the agent's drafted plan before approving
    plan_edited_by_user: Mapped[bool] = mapped_column(Boolean, default=False)

    # --- output ------------------------------------------------------------
    # Final synthesized Markdown report text
    report_markdown: Mapped[str | None] = mapped_column(Text, default=None)
    # Error message if task failed or was reaped
    error: Mapped[str | None] = mapped_column(Text, default=None)
    # Unique share token for unauthenticated public access
    share_id: Mapped[str | None] = mapped_column(String(32), unique=True, default=None)
    # Whether the task report is publicly accessible via its share link
    is_public: Mapped[bool] = mapped_column(Boolean, default=False)

    # --- accounting (spend caps read these) --------------------------------
    # Fresh input tokens consumed across all turns
    input_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Output tokens generated across all turns
    output_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Prompt tokens read from provider cache (discounted rate)
    cache_read_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Prompt tokens written to provider cache
    cache_write_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Total distinct web searches executed
    searches_used: Mapped[int] = mapped_column(Integer, default=0)
    # Shown on the approval gate before the person commits to the spend, and
    # compared against `actual_cost_usd` on the finished report.
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, default=None)
    # Cumulative actual dollar cost calculated from token counts and provider pricing
    actual_cost_usd: Mapped[float] = mapped_column(Float, default=0.0)
    # Output of app.agent.citations.audit_citations - which cited URLs were
    # actually retrieved, and which the model invented.
    citation_report: Mapped[dict | None] = mapped_column(JSON, default=None)
    # LLM Provider name (e.g. anthropic, openai, gemini)
    provider: Mapped[str | None] = mapped_column(String(32), default=None)
    # Specific model identifier used for this task (e.g. claude-opus-5)
    model: Mapped[str | None] = mapped_column(String(64), default=None)

    # Creation timestamp
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    # Last update timestamp
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )
    # Completion timestamp (set when marked complete)
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None
    )
    # Bumped by the worker while a run is alive. A task in a running state with
    # a stale heartbeat has lost its worker (redeploy, crash) and is reaped.
    heartbeat_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None
    )

    # ORM relationships
    user: Mapped[User] = relationship(back_populates="tasks")
    events: Mapped[list["TaskEvent"]] = relationship(
        back_populates="task",
        cascade="all, delete-orphan",
        order_by="TaskEvent.created_at",
    )
    sources: Mapped[list["Source"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )
    turns: Mapped[list["LLMTurn"]] = relationship(
        back_populates="task",
        cascade="all, delete-orphan",
        order_by="LLMTurn.created_at",
    )


class TaskEvent(Base):
    """Append-only progress log. The UI polls these to render a live timeline."""

    __tablename__ = "task_events"

    # Unique event identifier
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    # Associated research task
    task_id: Mapped[str] = mapped_column(
        ForeignKey("research_tasks.id", ondelete="CASCADE"), index=True
    )
    # Event category (status | search | thought | error | warning)
    kind: Mapped[str] = mapped_column(String(32))
    # Human-readable progress description
    message: Mapped[str] = mapped_column(Text)
    # Structured metadata (query, parameters, estimate details)
    data: Mapped[dict | None] = mapped_column(JSON, default=None)
    # Event timestamp
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    # Monotonic per-task cursor so the UI can ask for "events after N" instead
    # of refetching the whole task on every poll.
    seq: Mapped[int] = mapped_column(Integer, default=0, index=True)

    task: Mapped[ResearchTask] = relationship(back_populates="events")

    # Composite index for fast incremental polling queries: SELECT ... WHERE task_id = ? AND seq > ?
    __table_args__ = (Index("ix_task_events_task_seq", "task_id", "seq"),)


class Source(Base):
    """A page the agent actually read, kept so reports can cite and users can veto."""

    __tablename__ = "sources"
    # Ensure a single task does not store duplicate URLs
    __table_args__ = (UniqueConstraint("task_id", "url", name="uq_source_task_url"),)

    # Unique source identifier
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    # Associated research task
    task_id: Mapped[str] = mapped_column(
        ForeignKey("research_tasks.id", ondelete="CASCADE"), index=True
    )
    # Full URL of the retrieved web page
    url: Mapped[str] = mapped_column(Text)
    # Page title extracted by search provider
    title: Mapped[str] = mapped_column(Text, default="")
    # Extracted text snippet from search results
    snippet: Mapped[str] = mapped_column(Text, default="")
    # Human veto flag: True if user excluded this source from subsequent prompt turns
    excluded: Mapped[bool] = mapped_column(Boolean, default=False)
    # Retrieval timestamp
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    task: Mapped[ResearchTask] = relationship(back_populates="sources")


class LLMTurn(Base):
    """One model call. Makes a bad report debuggable and cost estimates tunable."""

    __tablename__ = "llm_turns"

    # Unique turn record identifier
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_uuid)
    # Associated research task
    task_id: Mapped[str] = mapped_column(
        ForeignKey("research_tasks.id", ondelete="CASCADE"), index=True
    )
    # Execution phase: planning | research | finalise
    phase: Mapped[str] = mapped_column(String(16))
    # Provider adapter used (anthropic, openai, gemini, etc.)
    provider: Mapped[str] = mapped_column(String(32))
    # Model identifier invoked (e.g. claude-opus-5)
    model: Mapped[str] = mapped_column(String(64))
    # Input tokens billed for this turn
    input_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Output tokens billed for this turn
    output_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Cache read tokens for this turn
    cache_read_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Cache write tokens for this turn
    cache_write_tokens: Mapped[int] = mapped_column(Integer, default=0)
    # Dollar cost calculated for this single turn
    cost_usd: Mapped[float] = mapped_column(Float, default=0.0)
    # Provider round-trip latency in milliseconds
    latency_ms: Mapped[int] = mapped_column(Integer, default=0)
    # Number of parallel tool calls emitted by the model in this turn
    tool_calls: Mapped[int] = mapped_column(Integer, default=0)
    # Model stop reason (end_turn, tool_use, max_tokens, refusal)
    stop_reason: Mapped[str | None] = mapped_column(String(32), default=None)
    # Number of retry attempts required to complete this turn successfully
    attempts: Mapped[int] = mapped_column(Integer, default=1)
    # Turn execution timestamp
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    task: Mapped[ResearchTask] = relationship(back_populates="turns")

